---
# New collections of modules
collections:
  modules:
    output: true

plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-scholar
exclude:
- ".gitignore"
- ".jekyll-cache"
scholar:
  bibtex_filters: [latex, markdown, tiny]
  style: apa
  locale: en

  source: ./_bibliography
